// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVzNNtEAU-R8eyIYXR84iaihV-9_2CSIo',
    appId: '1:1025984387707:web:a46c1084ca3b7d7c9c20de',
    messagingSenderId: '1025984387707',
    projectId: 'tip-pay-2a425',
    authDomain: 'tip-pay-2a425.firebaseapp.com',
    storageBucket: 'tip-pay-2a425.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAM4M7rOSJfFgSLXOhOqML2_y_pLNMcY4',
    appId: '1:1025984387707:android:ab16f44dc168106f9c20de',
    messagingSenderId: '1025984387707',
    projectId: 'tip-pay-2a425',
    storageBucket: 'tip-pay-2a425.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWLPVUaIfKBzbnlGurqQMF7eqOGwVabzI',
    appId: '1:1025984387707:ios:7a2e3a4d67a9e5fc9c20de',
    messagingSenderId: '1025984387707',
    projectId: 'tip-pay-2a425',
    storageBucket: 'tip-pay-2a425.appspot.com',
    iosClientId: '1025984387707-g7t3a3tbm6qreu8q0f089rl3f0pcitbu.apps.googleusercontent.com',
    iosBundleId: 'com.example.tipPay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWLPVUaIfKBzbnlGurqQMF7eqOGwVabzI',
    appId: '1:1025984387707:ios:7a2e3a4d67a9e5fc9c20de',
    messagingSenderId: '1025984387707',
    projectId: 'tip-pay-2a425',
    storageBucket: 'tip-pay-2a425.appspot.com',
    iosClientId: '1025984387707-g7t3a3tbm6qreu8q0f089rl3f0pcitbu.apps.googleusercontent.com',
    iosBundleId: 'com.example.tipPay',
  );
}
